"""pins refresh (maintainers): the download hashes in config/setup-pins.json
and the game's uv.lock, then the newer heads of the toolkit branch and of
the CLI next to the shas game.toml pins. game.toml itself is never written:
moving a pin is an edit a maintainer makes and the game's commit reviews."""

import json
import os
import shutil
import subprocess
import tempfile
import urllib.request

from . import env, fetch, host
from .host import CliError

CLI_BRANCH = "main"


def _get_json(url):
    req = urllib.request.Request(
        url,
        headers={"User-Agent": "%s-pins" % host.prog(), "Accept": "application/vnd.github+json"},
    )
    with urllib.request.urlopen(req) as r:
        return json.load(r)


def remote_head(url, branch):
    """The commit a remote branch points at (git ls-remote), or None."""
    if not url or not shutil.which("git"):
        return None
    r = subprocess.run(
        ["git", "ls-remote", url, "refs/heads/" + branch],
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
    )
    words = r.stdout.decode().split()
    return words[0] if r.returncode == 0 and words else None


def head_report(what, url, branch, pinned):
    head = remote_head(url, branch)
    if head is None:
        return "%-8s pinned %s; %s %s: not reachable" % (
            what + ":",
            pinned[:12],
            url or "(no url)",
            branch,
        )
    if head == pinned:
        return "%-8s pinned %s = %s head" % (what + ":", pinned[:12], branch)
    return "%-8s pinned %s; %s head is %s (move the pin in game.toml if you want it)" % (
        what + ":",
        pinned[:12],
        branch,
        head[:12],
    )


def pins_refresh():
    """The GitHub and SourceForge pins in setup-pins.json, then the Python
    half: `uv lock --upgrade` re-resolves the game's uv.lock (its
    pyproject.toml keeps capstone and pefile on their exact versions)."""
    g = host.g()
    uv, _ = env.find_uv()
    tag = fetch.mingw_tag()
    rel = _get_json("https://api.github.com/repos/mstorsjo/llvm-mingw/releases/tags/%s" % tag)
    want = sorted(set(v.format(tag=tag) for v in fetch.MINGW_ASSETS.values()))
    assets = {}
    for a in rel["assets"]:
        if a["name"] in want:
            if not (a.get("digest") or "").startswith("sha256:"):
                raise CliError("%s has no sha256 digest in the release API" % a["name"])
            assets[a["name"]] = {
                "url": a["browser_download_url"],
                "sha256": a["digest"][len("sha256:") :],
                "size": a["size"],
            }
    missing = set(want) - set(assets)
    if missing:
        raise CliError("llvm-mingw %s lacks %s" % (tag, ", ".join(sorted(missing))))
    # SourceForge publishes no sha256: hash the download here, once, and
    # pin that (trust on first use by the maintainer; setup then checks it).
    nsis_version = g.m["toolchain"]["nsis"]
    nsis_url = "https://sourceforge.net/projects/nsis/files/NSIS%%203/%s/nsis-%s.zip/download" % (
        nsis_version,
        nsis_version,
    )
    with tempfile.TemporaryDirectory() as tmp:
        p = os.path.join(tmp, "nsis.zip")
        with (
            urllib.request.urlopen(
                urllib.request.Request(nsis_url, headers={"User-Agent": "%s-pins" % host.prog()})
            ) as r,
            open(p, "wb") as f,
        ):
            shutil.copyfileobj(r, f)
        nsis = {
            "version": nsis_version,
            "url": nsis_url,
            "sha256": host.sha256_path(p),
            "size": os.path.getsize(p),
        }
    pins = {
        "_comment": "Generated by '%s pins refresh'. setup checks every download against these."
        % host.prog(),
        "llvm_mingw": {"tag": tag, "assets": assets},
        "nsis": nsis,
    }
    with open(g.pins, "w", newline="\n") as f:
        json.dump(pins, f, indent=2, sort_keys=True)
        f.write("\n")
    host.run([uv, "lock", "--upgrade", "--project", g.root], env=env.uv_env())
    host.say("wrote %s, %s" % (os.path.relpath(g.pins, g.root), os.path.relpath(g.uv_lock, g.root)))
    tk, cli = g.m["toolkit"], g.m["cli"]
    host.say(head_report("toolkit", tk["url"], tk["branch"], tk["commit"]))
    host.say(head_report("cli", cli["url"], CLI_BRANCH, cli["commit"]))
